### ISSUE TITLE
Add visual monitor

### ISSUE THREAD

**Issue by mldk-tech** [Gizra-Shoov/ness-tech#1]

**Comment by DavidKohav** [comment]
![1280](https://cloud.githubusercontent.com/assets/5812423/13141939/958c119a-d642-11e5-9bac-b6028bc61f19.jpg)

**Comment by mldk-tech** [comment]
https://app.shoov.io/#/screenshots/22546

**Comment by mldk-tech** [comment]
https://gfycat.com/SpotlessHeavenlyDikkops

**Comment by amitaibu** [comment]
:+1:
